services:
  liquid-auth:
    build: .
    env_file:
      - .env.docker
    expose:
      - "3000"
    depends_on:
      - redis
      - mongo
      - falconsrv
    environment:
      - FALCON_SERVICE_URL=http://falconsrv:3002
      - DB_HOST=mongo:27017
      - DB_USERNAME=${DB_USERNAME:-algorand}
      - DB_PASSWORD=${DB_PASSWORD:-algorand}
      - DB_NAME=${DB_USERNAME:-algorand}
      - DB_ATLAS=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=
      - ANDROID_SHA256HASH=${ANDROID_SHA256HASH}
      - ANDROID_PACKAGENAME=${ANDROID_PACKAGENAME:-com.michaeltchuang.walletsdk.demo}
      - ALGOD_SERVER=${ALGOD_SERVER:-https://mainnet-api.4160.nodely.dev}
    labels:
      # CORS middleware labels
      - traefik.http.middlewares.lqacors.headers.accesscontrolalloworiginlist=*
      - traefik.http.middlewares.lqacors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS
      - traefik.http.middlewares.lqacors.headers.accesscontrolallowheaders=Authorization,Content-Type,Accept,Origin
      - traefik.http.middlewares.cors.headers.accesscontrolalloworiginlistregex=.*
      - traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true
      - traefik.http.middlewares.lqacors.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.lqacors.headers.addvaryheader=true
  falconsrv:
    build:
      context: ./falconserver
    expose:
      - "3002"
  redis:
    image: redis
    expose:
      - "6379"
  mongo:
    image: mongo:7.0
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-fido}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-algorand}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-algorand}
    volumes:
      - mongo:/data/db
volumes:
  mongo:
